fix(nvim): disable copilot on termux
Since copilot-language-server failed to start:
```
Error: Could not locate the bindings file. Tried:
→ /data/data/com.termux/files/home/.local/share/nvim/mason/packages/copilot-language-server/node_modules/@github/copilot-language-server/dist/build/vscode-policy-watcher.node
...
```